apiVersion: v1
kind: Service
metadata:
  name: build-gradle-image
  labels:
    app: build-gradle-image
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: build-gradle-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-gradle-image
  labels:
    app: build-gradle-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-gradle-image
  template:
    metadata:
      labels:
        app: build-gradle-image
    spec:
      containers:
      - name: build-gradle-image
        image: spring-kafka-pubsub
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgresql:5432/messages
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: s3cr3t
