spring:
  kafka:
    bootstrap-servers: kafka:9092
    listener:
      ack-mode: manual_immediate
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
